version: '3.8'

services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - sql-server

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=your_password  # Reemplaza con tu contraseña segura
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
